name: mine_venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - psycopg2
  - pandas
  - numpy
  - boto3
  - pillow
  - python-dotenv
  - pip:
    - fastapi==0.109.0
    - uvicorn==0.27.0
    - kafka-python==2.0.2
    - sqlalchemy==2.0.27
    - pydantic==2.6.1
    - python-multipart==0.0.9
    - apscheduler==3.10.4
    - email-validator
    - black
    - flake8
    - pytest